/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kstock;

import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import jdk.nashorn.internal.objects.NativeArray;

/**
 *
 * @author Mayur
 */
public class AddItemMaster extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddItemMaster
     */
    public AddItemMaster() {
        
        initComponents();
        String itemList[] ={"ANAJ","KATHOD","DAL","USE & THROW","BISCUITS","ASSECENCES"};
        for (String itemList1 : itemList) {
            category_combo.addItem(itemList1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        addItem_form = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addItembtn = new javax.swing.JButton();
        resetItembtn = new javax.swing.JButton();
        category_combo = new javax.swing.JComboBox<>();

        setBorder(null);
        setDoubleBuffered(true);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel5.setText("Item Master");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        itemName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        itemName.setAutoscrolls(false);
        itemName.setCaretColor(new java.awt.Color(153, 153, 255));
        itemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemNameKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel6.setText("Item Name");

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel7.setText("Category");

        addItembtn.setBackground(new java.awt.Color(51, 102, 255));
        addItembtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addItembtn.setForeground(new java.awt.Color(255, 255, 255));
        addItembtn.setText("Save");
        addItembtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addItembtnMousePressed(evt);
            }
        });

        resetItembtn.setBackground(new java.awt.Color(51, 102, 255));
        resetItembtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        resetItembtn.setForeground(new java.awt.Color(255, 255, 255));
        resetItembtn.setText("Reset");
        resetItembtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetItembtnMousePressed(evt);
            }
        });

        category_combo.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        category_combo.setToolTipText("");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, category_combo, org.jdesktop.beansbinding.ObjectProperty.create(), category_combo, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout addItem_formLayout = new javax.swing.GroupLayout(addItem_form);
        addItem_form.setLayout(addItem_formLayout);
        addItem_formLayout.setHorizontalGroup(
            addItem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addItem_formLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(addItem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addItem_formLayout.createSequentialGroup()
                        .addComponent(addItembtn)
                        .addGap(28, 28, 28)
                        .addComponent(resetItembtn))
                    .addComponent(jLabel6)
                    .addComponent(itemName, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(category_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addItem_formLayout.setVerticalGroup(
            addItem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItem_formLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(addItem_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addItembtn)
                    .addComponent(resetItembtn))
                .addGap(0, 228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addItem_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addItem_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameKeyReleased
        itemName.setText(itemName.getText().toUpperCase());
    }//GEN-LAST:event_itemNameKeyReleased

    private void addItembtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItembtnMousePressed
        System.out.println(itemName.getText());
        System.out.println(category_combo.getSelectedItem().toString());
    }//GEN-LAST:event_addItembtnMousePressed

    private void resetItembtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetItembtnMousePressed
        itemName.setText("");
        category_combo.setSelectedIndex(0);
    }//GEN-LAST:event_resetItembtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addItem_form;
    private javax.swing.JButton addItembtn;
    private javax.swing.JComboBox<String> category_combo;
    private javax.swing.JTextField itemName;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton resetItembtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
