/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kstock;

import javax.swing.ButtonGroup;

/**
 *
 * @author Mayur
 */
public class AddStockMaster extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStockMaster
     */
    public AddStockMaster() {
        initComponents();
        initialSetup();
    }
    private String radioGroup ="Seva";
    
    private void initialSetup(){
        ButtonGroup bg = new ButtonGroup();
        bg.add(sevaRadio);
        bg.add(byPaymentRadio);
        sevaRadio.setSelected(true);
        this.gstTxtField.setEditable(false);
        this.chkDateTxtField.setEditable(false);
        this.chkNumberTxtField.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stockMaster_form = new javax.swing.JPanel();
        supplierName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        supplierName1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        supplierName2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        supplierName3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        supplierName4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        supplierName5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        supplierName6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        gstTxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        supplierName8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        chkNumberTxtField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        chkDateTxtField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        supplierName11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        addsupplierbtn = new javax.swing.JButton();
        resetSupplierbtn = new javax.swing.JButton();
        sevaRadio = new javax.swing.JRadioButton();
        byPaymentRadio = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(null);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel1.setText("Stock Master");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supplierName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName.setAutoscrolls(false);
        supplierName.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierNameKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel6.setText("Bill Date");

        supplierName1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName1.setAutoscrolls(false);
        supplierName1.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierName1KeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel7.setText("Date");

        supplierName2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName2.setAutoscrolls(false);
        supplierName2.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierName2KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel8.setText("Supplier Name");

        supplierName3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName3.setAutoscrolls(false);
        supplierName3.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierName3KeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel9.setText("Invoice Number");

        supplierName4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName4.setAutoscrolls(false);
        supplierName4.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierName4KeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel10.setText("Item Name");

        supplierName5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName5.setAutoscrolls(false);
        supplierName5.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierName5KeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel11.setText("Quantity");

        supplierName6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName6.setAutoscrolls(false);
        supplierName6.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierName6KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel12.setText("Unit Price");

        gstTxtField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        gstTxtField.setAutoscrolls(false);
        gstTxtField.setCaretColor(new java.awt.Color(153, 153, 255));
        gstTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gstTxtFieldKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel13.setText("GST %");

        supplierName8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName8.setAutoscrolls(false);
        supplierName8.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierName8KeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel14.setText("Bill Amount");

        chkNumberTxtField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        chkNumberTxtField.setAutoscrolls(false);
        chkNumberTxtField.setCaretColor(new java.awt.Color(153, 153, 255));
        chkNumberTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chkNumberTxtFieldKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel15.setText("Cheque Number");

        chkDateTxtField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        chkDateTxtField.setAutoscrolls(false);
        chkDateTxtField.setCaretColor(new java.awt.Color(153, 153, 255));
        chkDateTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chkDateTxtFieldKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel16.setText("Cheque Date");

        supplierName11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName11.setAutoscrolls(false);
        supplierName11.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierName11KeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel17.setText("Reference");

        addsupplierbtn.setBackground(new java.awt.Color(51, 102, 255));
        addsupplierbtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addsupplierbtn.setForeground(new java.awt.Color(255, 255, 255));
        addsupplierbtn.setText("Save");
        addsupplierbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addsupplierbtnMousePressed(evt);
            }
        });

        resetSupplierbtn.setBackground(new java.awt.Color(51, 102, 255));
        resetSupplierbtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        resetSupplierbtn.setForeground(new java.awt.Color(255, 255, 255));
        resetSupplierbtn.setText("Reset");
        resetSupplierbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetSupplierbtnMousePressed(evt);
            }
        });

        sevaRadio.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        sevaRadio.setText("Seva");
        sevaRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevaRadioMouseClicked(evt);
            }
        });
        sevaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevaRadioActionPerformed(evt);
            }
        });

        byPaymentRadio.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        byPaymentRadio.setText("By Payment");
        byPaymentRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                byPaymentRadioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout stockMaster_formLayout = new javax.swing.GroupLayout(stockMaster_form);
        stockMaster_form.setLayout(stockMaster_formLayout);
        stockMaster_formLayout.setHorizontalGroup(
            stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stockMaster_formLayout.createSequentialGroup()
                .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(supplierName1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(supplierName3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(supplierName6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(chkNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(stockMaster_formLayout.createSequentialGroup()
                                .addComponent(sevaRadio)
                                .addGap(18, 18, 18)
                                .addComponent(byPaymentRadio)))
                        .addGap(44, 44, 44)
                        .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(supplierName4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(gstTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(chkDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(supplierName2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(supplierName5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(supplierName8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(supplierName11, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addsupplierbtn)
                        .addGap(18, 18, 18)
                        .addComponent(resetSupplierbtn)))
                .addGap(110, 110, 110))
            .addComponent(jSeparator1)
        );
        stockMaster_formLayout.setVerticalGroup(
            stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockMaster_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevaRadio)
                    .addComponent(byPaymentRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gstTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockMaster_formLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierName11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(stockMaster_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addsupplierbtn)
                    .addComponent(resetSupplierbtn))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stockMaster_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockMaster_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameKeyReleased
        supplierName.setText(supplierName.getText().toUpperCase());
    }//GEN-LAST:event_supplierNameKeyReleased

    private void supplierName1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierName1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierName1KeyReleased

    private void supplierName2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierName2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierName2KeyReleased

    private void supplierName3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierName3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierName3KeyReleased

    private void supplierName4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierName4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierName4KeyReleased

    private void supplierName5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierName5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierName5KeyReleased

    private void supplierName6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierName6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierName6KeyReleased

    private void gstTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gstTxtFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gstTxtFieldKeyReleased

    private void supplierName8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierName8KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierName8KeyReleased

    private void chkNumberTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkNumberTxtFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNumberTxtFieldKeyReleased

    private void chkDateTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkDateTxtFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDateTxtFieldKeyReleased

    private void supplierName11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierName11KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierName11KeyReleased

    private void addsupplierbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addsupplierbtnMousePressed
        System.out.println(supplierName.getText());
        //System.out.println(cityName.getText());
        //System.out.println(refPersonName.getText());
    }//GEN-LAST:event_addsupplierbtnMousePressed

    private void resetSupplierbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetSupplierbtnMousePressed
        supplierName.setText("");
        //cityName.setText("");
        //refPersonName.setText("");
    }//GEN-LAST:event_resetSupplierbtnMousePressed

    private void sevaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevaRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sevaRadioActionPerformed

    private void byPaymentRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byPaymentRadioMouseClicked
        this.radioGroup = "Payment";
        this.gstTxtField.setEditable(true);
        this.chkDateTxtField.setEditable(true);
        this.chkNumberTxtField.setEditable(true);
    }//GEN-LAST:event_byPaymentRadioMouseClicked

    private void sevaRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevaRadioMouseClicked
        this.radioGroup = "Seva";
        this.gstTxtField.setEditable(false);
        this.chkDateTxtField.setEditable(false);
        this.chkNumberTxtField.setEditable(false);
    }//GEN-LAST:event_sevaRadioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsupplierbtn;
    private javax.swing.JRadioButton byPaymentRadio;
    private javax.swing.JTextField chkDateTxtField;
    private javax.swing.JTextField chkNumberTxtField;
    private javax.swing.JTextField gstTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton resetSupplierbtn;
    private javax.swing.JRadioButton sevaRadio;
    private javax.swing.JPanel stockMaster_form;
    private javax.swing.JTextField supplierName;
    private javax.swing.JTextField supplierName1;
    private javax.swing.JTextField supplierName11;
    private javax.swing.JTextField supplierName2;
    private javax.swing.JTextField supplierName3;
    private javax.swing.JTextField supplierName4;
    private javax.swing.JTextField supplierName5;
    private javax.swing.JTextField supplierName6;
    private javax.swing.JTextField supplierName8;
    // End of variables declaration//GEN-END:variables
}
