/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kstock;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Mayur
 */
public class SupplierMaster extends javax.swing.JInternalFrame {

    /**
     * Creates new form SupplierMaster
     */
    public SupplierMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        supplierName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cityName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        refPersonName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addsupplierbtn = new javax.swing.JButton();
        resetSupplierbtn = new javax.swing.JButton();

        setBorder(null);

        supplierName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supplierName.setAutoscrolls(false);
        supplierName.setCaretColor(new java.awt.Color(153, 153, 255));
        supplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierNameKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel6.setText("Supplier Name");

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel5.setText("Supplier Master");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cityName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cityName.setAutoscrolls(false);
        cityName.setCaretColor(new java.awt.Color(153, 153, 255));
        cityName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityNameKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel7.setText("City Name");

        refPersonName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        refPersonName.setAutoscrolls(false);
        refPersonName.setCaretColor(new java.awt.Color(153, 153, 255));
        refPersonName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                refPersonNameKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel8.setText("Reference Person Name");

        addsupplierbtn.setBackground(new java.awt.Color(51, 102, 255));
        addsupplierbtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addsupplierbtn.setForeground(new java.awt.Color(255, 255, 255));
        addsupplierbtn.setText("Save");
        addsupplierbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addsupplierbtnMousePressed(evt);
            }
        });

        resetSupplierbtn.setBackground(new java.awt.Color(51, 102, 255));
        resetSupplierbtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        resetSupplierbtn.setForeground(new java.awt.Color(255, 255, 255));
        resetSupplierbtn.setText("Reset");
        resetSupplierbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetSupplierbtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addsupplierbtn)
                        .addGap(18, 18, 18)
                        .addComponent(resetSupplierbtn))
                    .addComponent(jLabel8)
                    .addComponent(refPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cityName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cityName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addsupplierbtn)
                    .addComponent(resetSupplierbtn))
                .addGap(0, 134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameKeyReleased
        supplierName.setText(supplierName.getText().toUpperCase());
    }//GEN-LAST:event_supplierNameKeyReleased

    private void cityNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityNameKeyReleased
       cityName.setText(cityName.getText().toUpperCase());
    }//GEN-LAST:event_cityNameKeyReleased

    private void refPersonNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_refPersonNameKeyReleased
        refPersonName.setText(refPersonName.getText().toUpperCase());
    }//GEN-LAST:event_refPersonNameKeyReleased

    private void addsupplierbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addsupplierbtnMousePressed
        System.out.println(supplierName.getText());
        System.out.println(cityName.getText());
        System.out.println(refPersonName.getText());
    }//GEN-LAST:event_addsupplierbtnMousePressed

    private void resetSupplierbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetSupplierbtnMousePressed
        supplierName.setText("");
        cityName.setText("");
        refPersonName.setText("");
    }//GEN-LAST:event_resetSupplierbtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsupplierbtn;
    private javax.swing.JTextField cityName;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField refPersonName;
    private javax.swing.JButton resetSupplierbtn;
    private javax.swing.JTextField supplierName;
    // End of variables declaration//GEN-END:variables
}
